### ISSUE TITLE
Problems during make for hin-pan pair

### ISSUE THREAD

**Issue by priyankmodiPM** [apertium/apertium-hin-pan#2]
I get this error while compiling the makefile for the hin-pan pair : make: *** No rule to make target '../apertium-hin/hin.autopgen.bin', needed by 'pan-hin.autopgen.bin'.  Stop.

Commenting in the makefile(Makefile.am) runs the tests incorrectly, even though the make completes without errors.

**Comment by ftyers** [comment]
I don't see how you could get that error seeing as the entries are commented out:

```
$ grep -nHr pgen .
./Makefile.am:192:#$(PREFIX1).autopgen.bin: $(AP_SRC2)/$(LANG2).autopgen.bin
./Makefile.am:195:#$(PREFIX2).autopgen.bin: $(AP_SRC1)/$(LANG1).autopgen.bin
./Makefile.in:311:#$(PREFIX1).autopgen.bin: $(AP_SRC2)/$(LANG2).autopgen.bin
./Makefile.in:314:#$(PREFIX2).autopgen.bin: $(AP_SRC1)/$(LANG1).autopgen.bin
./Makefile:311:#$(PREFIX1).autopgen.bin: $(AP_SRC2)/$(LANG2).autopgen.bin
./Makefile:314:#$(PREFIX2).autopgen.bin: $(AP_SRC1)/$(LANG1).autopgen.bin
```

See: https://github.com/apertium/apertium-hin-pan/blob/b8cea06c4748b24db7eb7e94b455a491425c04b5/Makefile.am#L188

The system seems to work for me, although there are a lot of generation errors:

```
$ head -1  texts/story.hin.txt  | apertium -d . hin-pan_Guru
#ਗਿਰਜਾ #ਅਜ੍ਜ #ਫਿਰ #ਇਹ #ਔਰਤ ਨੂੰ ਨਾਲ #ਲਿਆਉ *था#.#ਉਹੋ #ਦੁਬਲਾ #ਪਤਲਾ #ਮੋਟਾ-#ਮੋਟਾ #ਅੱਖ #ਤਿਖਣ #ਨੱਕ #ਅਤੇ #ਸਾਉਲਾ #ਰਂਗ #ਵਾਲਾ #ਔਰਤ#.#
```

**Comment by priyankmodiPM** [comment]
Could you send me the commit id for your version, i believe following the steps on : http://wiki.apertium.org/wiki/How_to_bootstrap_a_new_pair gave me a different version as line numbers are different(the lines are of course not commented) and texts directory doesn't exist. Thanks for the help.

**Comment by priyankmodiPM** [comment]
nvm, i figured it out. Thanks.
