### ISSUE TITLE
Part of multiword embedded in another word.

### ISSUE THREAD

**Issue by priyankmodiPM** [apertium/apertium-hin-pan#5]
(1) राम के पास पांच सेब हैं > ਰਾਮ ਕੋਲ ਪੰਜ ਸੇਬ ਹਨ
(2) राम पास हो गया > ਰਾਮ ਪਾਸ ਹੋ ਗਿਆ
While this can be handled by defining the bidix entry "के पास" > "ਕੋਲ" 

But how to achieve the same for cases like :
उसके पास > ਉਸ ਕੋਲ
उनके पास > ਉਹਨਾਂ ਕੋਲ
सबके पास > ਸਆਰਿਆਂ ਕੋਲ
where the 'ke' postposition is embedded.

**Comment by ftyers** [comment]
@priyankmodiPM can you give the input and output in terms of analyses?

**Comment by priyankmodiPM** [comment]
✓राम के पास पांच सेब हैं > ਰਾਮ ਕੋਲ ਪੰਜ ਸੇਬ ਹਨ
✓Ram ke paas paanch seb hain > Ram kol panj seb han
✓ Ram has 5 apples
```
^राम/राम<np><ant><m><sg><nom>$ ^के पास/के पास<post>$ ^पांच/पांच<num>$ ^सेब/सेब<n><m><sg><nom>/सेब<n><m><sg><obl>/सेब<n><m><pl><nom>$ ^हैं/हो<vbser><pres><p3><mf><pl>/हो<vbser><pres><p1><mf><pl>$

^ਰਾਮ/ਰਾਮ<np><ant><m><sg><nom>$ ^ਕੋਲ/ਕੋਲ<post>$ ^ਪੰਜ/ਪੰਜ<num>$ ^ਸੇਬ/*ਸੇਬ$ ^ਹਨ/ਹੋ<vbser><pres><p1><mf><pl>/ਹੋ<vbser><pres><p3><mf><pl>$
```
-----------

✓राम पास हो गया > ਰਾਮ ਪਾਸ ਹੋ ਗਿਆ
✓ram pass ho gaya > ram pass ho gia
✓Ram passed(the exam)
```
^राम/राम<np><ant><m><sg><nom>$ ^पास हो/पास होना<vblex><iv><prs><p2><pl>/पास होना<vblex><iv><imp><p2><sg>/पास होना<vblex><iv><imp><p2><pl>$ ^गया/जा<vblex><iv><perf><m><sg>$

^ਰਾਮ/ਰਾਮ<np><ant><m><sg><nom>$ ^ਪਾਸ/*ਪਾਸ$ ^ਹੋ/ਹੋ<vbser><imp><p2><sg>/ਹੋ<vbser><imp><p2><pl>/ਹੋ<vbser><pres><p2><mf><pl>/ਹੋਣਾ<vblex><iv><prs><p2><sg>/ਹੋਣਾ<vblex><iv><prs><p2><pl>/ਹੋਣਾ<vblex><iv><imp><p2><sg>/ਹੋਣਾ<vblex><iv><imp><p2><pl>$ ^ਗਿਆ/ਜਾ<vblex><iv><perf><m><sg>$
```
------------------

Goal : 
```
SL : ^उसके/यह<prn><dem><p3><mf><sg><dist><gen>$ ^पास/पास<adv>$
TL : ^ਉਸ/ਉ<prn><pers><p3><mf><sg><obl>/ਇਹ<prn><dem><p3><mf><sg><dist><obl>$ ^ਕੋਲ/ਕੋਲ<post>$
```

**Comment by khannatanmai** [comment]
@priyankmodiPM 
First of all, I wouldn't handle "ke paas" as one lexical unit. ke is the postposition for Ram, and paas is a separate postposition. These can combine to "kol" in Punjabi.

As for your second problem, with uske, iske, etc. I would analyse those as "us+ke" , "iss+ke" so that pretransfer breaks it up and the bidix can translate "ke paas" as one unit (maybe using separable? - if separable still works after pretransfer) @ftyers

**Comment by ftyers** [comment]
@khannatanmai yes, separable will work then... also having `+के<post>` would work instead of `<gen>`., e.g.
```
 	 <e><p><l>उसके</l><r>यह<s n="prn"/><s n="dem"/><s n="p3"/><s n="mf"/><s n="sg"/><s n="dist"/><j/>के<s n="post"/></r></p></e>
```

**Comment by khannatanmai** [comment]
@priyankmodiPM if you think that the "ke" in "ke paas" is different from the usual "ke" I guess I could understand that as well. I understand "Ram ke paas 5 seb hai" as "With Ram there are 5 apples".

**Comment by ftyers** [comment]
Hmm, it doesn't look to a different `के` to me, I think just the translation (to English) is deceptive.  Do whatever works for `hin-pan`. :)

**Comment by priyankmodiPM** [comment]
@khannatanmai no, it's the same "ke". I think your previous comment and spectie's example should solve it. "ke paas" was defined in the hindi dict as a single unit which would've worked for urd-hin.
